'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'Cards',
      [
        {
          english: 'Apple',
          russian: 'Яблоко',
          imagePath: '/uploads/food/apple.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Banana',
          russian: 'Банан',
          imagePath: '/uploads/food/banana.jpg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bread',
          russian: 'Хлеб',
          imagePath: '/uploads/food/bread.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Cheese',
          russian: 'Сыр',
          imagePath: '/uploads/food/cheese.jpg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Chicken',
          russian: 'Курица',
          imagePath: '/uploads/food/chicken.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Egg',
          russian: 'Яйцо',
          imagePath: '/uploads/food/egg.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Fish',
          russian: 'Рыба',
          imagePath: '/uploads/food/fish.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Milk',
          russian: 'Молоко',
          imagePath: '/uploads/food/milk.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Rice',
          russian: 'Рис',
          imagePath: '/uploads/food/rice.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Soup',
          russian: 'Суп',
          imagePath: '/uploads/food/soup.jpeg',
          themeId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          english: 'Car',
          russian: 'Машина',
          imagePath: '/uploads/transport/car.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bus',
          russian: 'Автобус',
          imagePath: '/uploads/transport/bus.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Train',
          russian: 'Поезд',
          imagePath: '/uploads/transport/train.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bicycle',
          russian: 'Велосипед',
          imagePath: '/uploads/transport/bicycle.jpeg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Airplane',
          russian: 'Самолёт',
          imagePath: '/uploads/transport/airplane.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Boat',
          russian: 'Лодка',
          imagePath: '/uploads/transport/boat.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Motorcycle',
          russian: 'Мотоцикл',
          imagePath: '/uploads/transport/motorcycle.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Taxi',
          russian: 'Такси',
          imagePath: '/uploads/transport/taxi.png',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Subway',
          russian: 'Метро',
          imagePath: '/uploads/transport/subway.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Helicopter',
          russian: 'Вертолёт',
          imagePath: '/uploads/transport/helicopter.jpg',
          themeId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          english: 'Cat',
          russian: 'Кошка',
          imagePath: '/uploads/animals/cat.jpg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Dog',
          russian: 'Собака',
          imagePath: '/uploads/animals/dog.jpeg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Elephant',
          russian: 'Слон',
          imagePath: '/uploads/animals/elephant.jpeg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Lion',
          russian: 'Лев',
          imagePath: '/uploads/animals/lion.webp',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Tiger',
          russian: 'Тигр',
          imagePath: '/uploads/animals/tiger.webp',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Monkey',
          russian: 'Обезьяна',
          imagePath: '/uploads/animals/monkey.jpg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Giraffe',
          russian: 'Жираф',
          imagePath: '/uploads/animals/giraffe.png',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Bear',
          russian: 'Медведь',
          imagePath: '/uploads/animals/bear.jpeg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Rabbit',
          russian: 'Кролик',
          imagePath: '/uploads/animals/rabbit.jpeg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Horse',
          russian: 'Лошадь',
          imagePath: '/uploads/animals/horse.jpeg',
          themeId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          english: 'Shirt',
          russian: 'Рубашка',
          imagePath: '/uploads/clothes/shirt.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Pants',
          russian: 'Брюки',
          imagePath: '/uploads/clothes/pants.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Dress',
          russian: 'Платье',
          imagePath: '/uploads/clothes/dress.jpg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Jacket',
          russian: 'Куртка',
          imagePath: '/uploads/clothes/jacket.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Shoes',
          russian: 'Обувь',
          imagePath: '/uploads/clothes/shoes.jpg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Hat',
          russian: 'Шляпа',
          imagePath: '/uploads/clothes/hat.jpg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Socks',
          russian: 'Носки',
          imagePath: '/uploads/clothes/socks.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Skirt',
          russian: 'Юбка',
          imagePath: '/uploads/clothes/skirt.jpg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Coat',
          russian: 'Пальто',
          imagePath: '/uploads/clothes/coat.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'T-shirt',
          russian: 'Футболка',
          imagePath: '/uploads/clothes/tshirt.jpeg',
          themeId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          english: 'Tree',
          russian: 'Дерево',
          imagePath: '/uploads/nature/tree.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Flower',
          russian: 'Цветок',
          imagePath: '/uploads/nature/flower.jpeg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'River',
          russian: 'Река',
          imagePath: '/uploads/nature/river.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Mountain',
          russian: 'Гора',
          imagePath: '/uploads/nature/mountain.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Forest',
          russian: 'Лес',
          imagePath: '/uploads/nature/forest.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Lake',
          russian: 'Озеро',
          imagePath: '/uploads/nature/lake.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Sky',
          russian: 'Небо',
          imagePath: '/uploads/nature/sky.jpeg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Sun',
          russian: 'Солнце',
          imagePath: '/uploads/nature/sun.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Moon',
          russian: 'Луна',
          imagePath: '/uploads/nature/moon.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          english: 'Star',
          russian: 'Звезда',
          imagePath: '/uploads/nature/star.jpg',
          themeId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Cards', null, {});
  },
};
